### ISSUE TITLE
Warning: Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by nvbach91** [felippe-regazio/php-hot-reloader#1]
Hello, first let me thank you for your work. It is very useful and I'm using your tool to teach my students.

I have the following issue where this warning appears on my page.
![image](https://user-images.githubusercontent.com/20724910/53242786-19fd1c00-36a6-11e9-9538-d2f580ca9710.png)
...and because of that, the page doesn't react to changes in linked files like CSS and JavaScript, but changes in PHP files still work.

The interesting part is that if I reduce the amount of output then the warning goes away and everything works OK.

My source code can be found here: https://github.com/nvbach91/4IZ278-2018-2019-LS/blob/master/www/nguv03/cv02/warning.php

I also tested this using plain html with no custom PHP at all and it seems like there is a certain amount of generated output at which the warning starts to show up.

I'm using PHP 7.3.1 in XAMPP

Thanks in advance!

**Comment by felippe-regazio** [comment]
Thank you nvbach91!!! Im on it. I`ll do some changes and we must have a fixed push this week.

**Comment by felippe-regazio** [comment]
Its an honor to me to know that this scripting is being used to teach. Thanks a lot nvbach. Really sorry for the gap to answer your issue. 

In fact, there is a problema with headers, processing order, and error reporting (when page crashs with reloader activated). This errors was fixed, i must ask you to download the hot-reloader again, or run a git pull in your fork.

About your problem: In your code, please add your hot reloader instance just before your <!DOCTYPE html> tag. As above:

```php
//PHP CODE...
?>
<?php
    require '../php-hot-reloader/hotreloader.php';
    $reloader = new HotReloader();
    $reloader->init();
?>
<!DOCTYPE html>
// PAGE CODE
```

The problem is becase we`re adding the reloader in the end of the page (my mistake, sorry). So, the server sends the headers with your code content (then, in the require, the php tries to modify those headers, and cannot because they`re was already sent). Il`l update the documentation. Thanks again nvbach91! Let me know the results.

**Comment by felippe-regazio** [comment]
Its an honor to me to know that this script is being used to teach purposes. Thanks a lot nvbach. Really sorry for the gap to answer your issue. 

In fact, there was a problem with headers, processing order, and error reporting (when page crashs with reloader activated). Maybe the link below can give us some light:

Ref: https://pt.stackoverflow.com/questions/4251/erro-cannot-modify-header-information-headers-already-sent

I made some changes in order to fix this issue.
I added a lot of html with the hotreloader, and got the same header already sent error.
So, i added a condition on the funcion which adds the etag on the hot reloader to not do it if already have headers. The js keeps watching and reloading the page normally after this first interation and the error has gone.

Thanks for your reply.
If you have any other problem please let me know. 

Regards!

**Comment by nvbach91** [comment]
@felippe-regazio Good one! It works perfectly now. Thanks a bunch!
